language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "No installs before script"

# Scripts to be run such as tests
before_script:
  - echo "No tests before script"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker-compose push  # does not work
  - docker tag reverseproxy "$DOCKER_USERNAME"/reverseproxy:v1
  - docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:v1
  - docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:v1
  - docker tag udagram-frontend:local "$DOCKER_USERNAME"/udagram-frontend:v1
  - docker push "$DOCKER_USERNAME"/reverseproxy:v1
  - docker push "$DOCKER_USERNAME"/udagram-api-feed:v1
  - docker push "$DOCKER_USERNAME"/udagram-api-user:v1
  - docker push "$DOCKER_USERNAME"/udagram-frontend:v1