language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "No installs before script"

# Scripts to be run such as tests
before_script:
  - echo "No tests before script"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push