apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  # name: backend-user-svc  # wrong! has to match exactly the name in nginx.conf
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    # service: backend-user
    app: backend-user